# Generated by Django 6.0.4 on 2026-05-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_question_view_count_alter_answer_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
