# Generated by Django 6.0.4 on 2026-05-26 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_answer_is_selected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bookmark',
            field=models.ManyToManyField(related_name='bookmark_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
